### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by stolinski** [johnantoni/meteor-svginjector#1]
I've added it to my Meteor app. There isn't any instructions and my .svg files aren't being injected.

**Comment by johnantoni** [comment]
Sorry,

Updated the readme.

https://github.com/johnantoni/meteor-svginjector/blob/master/README.md

Basically loads in iconic's SVGInjector library to render the SVG assets, using png assets for fallback https://github.com/iconic/SVGInjector

**Comment by stolinski** [comment]
Awesome! Thanks John.

**Comment by johnantoni** [comment]
No worries, let me know how it goes or if I need to update the package.

All the best,
